// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"time"
)

type Admin struct {
	ent.Schema
}

func (Admin) Fields() []ent.Field {
	return []ent.Field{
	field.UUID("id", uuid.UUID{}).Default(uuid.New).Immutable(),
	field.String("email").Unique().NotEmpty(),
	field.String("password_hash").NotEmpty(),
	field.String("name").Optional(),
	field.Time("created_at").Default(time.Now).Immutable()}
}
func (Admin) Edges() []ent.Edge {
	return nil
}
func (Admin) Annotations() []schema.Annotation {
	return nil
}
