// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

type Admin struct {
	ent.Schema
}

func (Admin) Fields() []ent.Field {
	return []ent.Field{field.UUID("id", uuid.UUID{}), field.String("email").Unique(), field.String("password_hash"), field.String("name").Optional(), field.Time("created_at")}
}
func (Admin) Edges() []ent.Edge {
	return nil
}
func (Admin) Annotations() []schema.Annotation {
	return nil
}
