// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"vinyl-store/ent/admin"
	"vinyl-store/ent/artist"
	"vinyl-store/ent/genre"
	"vinyl-store/ent/news"
	"vinyl-store/ent/order"
	"vinyl-store/ent/orderitem"
	"vinyl-store/ent/schema"
	"vinyl-store/ent/user"
	"vinyl-store/ent/vinyl"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescEmail is the schema descriptor for email field.
	adminDescEmail := adminFields[1].Descriptor()
	// admin.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	admin.EmailValidator = adminDescEmail.Validators[0].(func(string) error)
	// adminDescPasswordHash is the schema descriptor for password_hash field.
	adminDescPasswordHash := adminFields[2].Descriptor()
	// admin.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	admin.PasswordHashValidator = adminDescPasswordHash.Validators[0].(func(string) error)
	// adminDescCreatedAt is the schema descriptor for created_at field.
	adminDescCreatedAt := adminFields[4].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the created_at field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescID is the schema descriptor for id field.
	adminDescID := adminFields[0].Descriptor()
	// admin.DefaultID holds the default value on creation for the id field.
	admin.DefaultID = adminDescID.Default.(func() uuid.UUID)
	artistFields := schema.Artist{}.Fields()
	_ = artistFields
	// artistDescName is the schema descriptor for name field.
	artistDescName := artistFields[1].Descriptor()
	// artist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	artist.NameValidator = artistDescName.Validators[0].(func(string) error)
	// artistDescCreatedAt is the schema descriptor for created_at field.
	artistDescCreatedAt := artistFields[3].Descriptor()
	// artist.DefaultCreatedAt holds the default value on creation for the created_at field.
	artist.DefaultCreatedAt = artistDescCreatedAt.Default.(func() time.Time)
	// artistDescID is the schema descriptor for id field.
	artistDescID := artistFields[0].Descriptor()
	// artist.DefaultID holds the default value on creation for the id field.
	artist.DefaultID = artistDescID.Default.(func() uuid.UUID)
	genreFields := schema.Genre{}.Fields()
	_ = genreFields
	// genreDescName is the schema descriptor for name field.
	genreDescName := genreFields[1].Descriptor()
	// genre.NameValidator is a validator for the "name" field. It is called by the builders before save.
	genre.NameValidator = genreDescName.Validators[0].(func(string) error)
	// genreDescCreatedAt is the schema descriptor for created_at field.
	genreDescCreatedAt := genreFields[2].Descriptor()
	// genre.DefaultCreatedAt holds the default value on creation for the created_at field.
	genre.DefaultCreatedAt = genreDescCreatedAt.Default.(func() time.Time)
	// genreDescID is the schema descriptor for id field.
	genreDescID := genreFields[0].Descriptor()
	// genre.DefaultID holds the default value on creation for the id field.
	genre.DefaultID = genreDescID.Default.(func() uuid.UUID)
	newsFields := schema.News{}.Fields()
	_ = newsFields
	// newsDescTitle is the schema descriptor for title field.
	newsDescTitle := newsFields[1].Descriptor()
	// news.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	news.TitleValidator = newsDescTitle.Validators[0].(func(string) error)
	// newsDescContent is the schema descriptor for content field.
	newsDescContent := newsFields[2].Descriptor()
	// news.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	news.ContentValidator = newsDescContent.Validators[0].(func(string) error)
	// newsDescPublishedAt is the schema descriptor for published_at field.
	newsDescPublishedAt := newsFields[3].Descriptor()
	// news.DefaultPublishedAt holds the default value on creation for the published_at field.
	news.DefaultPublishedAt = newsDescPublishedAt.Default.(func() time.Time)
	// newsDescID is the schema descriptor for id field.
	newsDescID := newsFields[0].Descriptor()
	// news.DefaultID holds the default value on creation for the id field.
	news.DefaultID = newsDescID.Default.(func() uuid.UUID)
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[2].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(string)
	// orderDescTotalAmount is the schema descriptor for total_amount field.
	orderDescTotalAmount := orderFields[3].Descriptor()
	// order.DefaultTotalAmount holds the default value on creation for the total_amount field.
	order.DefaultTotalAmount = orderDescTotalAmount.Default.(float64)
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderFields[4].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
	orderitemFields := schema.OrderItem{}.Fields()
	_ = orderitemFields
	// orderitemDescQuantity is the schema descriptor for quantity field.
	orderitemDescQuantity := orderitemFields[3].Descriptor()
	// orderitem.DefaultQuantity holds the default value on creation for the quantity field.
	orderitem.DefaultQuantity = orderitemDescQuantity.Default.(int)
	// orderitemDescID is the schema descriptor for id field.
	orderitemDescID := orderitemFields[0].Descriptor()
	// orderitem.DefaultID holds the default value on creation for the id field.
	orderitem.DefaultID = orderitemDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	vinylFields := schema.Vinyl{}.Fields()
	_ = vinylFields
	// vinylDescTitle is the schema descriptor for title field.
	vinylDescTitle := vinylFields[1].Descriptor()
	// vinyl.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	vinyl.TitleValidator = vinylDescTitle.Validators[0].(func(string) error)
	// vinylDescPrice is the schema descriptor for price field.
	vinylDescPrice := vinylFields[2].Descriptor()
	// vinyl.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	vinyl.PriceValidator = vinylDescPrice.Validators[0].(func(float64) error)
	// vinylDescStockCount is the schema descriptor for stock_count field.
	vinylDescStockCount := vinylFields[3].Descriptor()
	// vinyl.StockCountValidator is a validator for the "stock_count" field. It is called by the builders before save.
	vinyl.StockCountValidator = vinylDescStockCount.Validators[0].(func(int32) error)
	// vinylDescCreatedAt is the schema descriptor for created_at field.
	vinylDescCreatedAt := vinylFields[7].Descriptor()
	// vinyl.DefaultCreatedAt holds the default value on creation for the created_at field.
	vinyl.DefaultCreatedAt = vinylDescCreatedAt.Default.(func() time.Time)
	// vinylDescID is the schema descriptor for id field.
	vinylDescID := vinylFields[0].Descriptor()
	// vinyl.DefaultID holds the default value on creation for the id field.
	vinyl.DefaultID = vinylDescID.Default.(func() uuid.UUID)
}
