// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Artist is the predicate function for artist builders.
type Artist func(*sql.Selector)

// Genre is the predicate function for genre builders.
type Genre func(*sql.Selector)

// News is the predicate function for news builders.
type News func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vinyl is the predicate function for vinyl builders.
type Vinyl func(*sql.Selector)
